import { ScaleType } from './scales';

export type TrackId = 'A' | 'B' | 'C' | 'D';

export interface LevelDefinition {
  levelNumber: number; // 1 to 10
  name: string;
  allowedDegrees: number[];
  phraseLength: number;
  targetChallenges: number;
  passThreshold: number; // 0.85 to 0.90
  description: string;
  pedagogicalFocus: string;
  tonalSupport: 'always' | 'periodic' | 'sparse';
  scaleType: ScaleType;
  maxInterval: number; // 1 = unison, 2 = step, 4 = third, 7 = fifth, 12 = octave
}

export interface TrackDefinition {
  id: TrackId;
  name: string;
  shortName: string;
  direction: string;
  mode: 'singing' | 'recognition' | 'melody-singing' | 'transcription';
  icon: string;
  color: string;
  description: string;
  levels: LevelDefinition[];
}

export const TRACKS: Record<TrackId, TrackDefinition> = {
  A: {
    id: 'A',
    name: 'Degree Singing',
    shortName: 'Singing',
    direction: 'See degree · audiate · sing · verify',
    mode: 'singing',
    icon: 'Mic',
    color: '#38bdf8',
    description: 'Internal hearing and active vocal retrieval. Look at the scale degree number, audiate its pitch against the tonal center, sing it, and then sound the reference to verify.',
    levels: [
      {
        levelNumber: 1,
        name: 'Anchors',
        allowedDegrees: [1, 3, 5],
        phraseLength: 1,
        targetChallenges: 18,
        passThreshold: 0.85,
        description: 'Establish tonic (1), mediant (3), and dominant (5) anchor points.',
        pedagogicalFocus: 'Establish 1, 3, and 5 with tonic reinforcement before every challenge.',
        tonalSupport: 'always',
        scaleType: 'major',
        maxInterval: 7,
      },
      {
        levelNumber: 2,
        name: 'Pentachord',
        allowedDegrees: [1, 2, 3, 4, 5],
        phraseLength: 1,
        targetChallenges: 20,
        passThreshold: 0.85,
        description: 'Introduce steps 2 and 4 to complete the lower pentachord.',
        pedagogicalFocus: 'Notice the gravitational pull of 4 to 3 and the buoyancy of 2.',
        tonalSupport: 'periodic',
        scaleType: 'major',
        maxInterval: 7,
      },
      {
        levelNumber: 3,
        name: 'Add Six',
        allowedDegrees: [1, 2, 3, 4, 5, 6],
        phraseLength: 1,
        targetChallenges: 20,
        passThreshold: 0.85,
        description: 'Introduce degree 6 as an expressive open color tone.',
        pedagogicalFocus: 'Contrast degree 6 against 5 and 1 without confusing with 4.',
        tonalSupport: 'periodic',
        scaleType: 'major',
        maxInterval: 7,
      },
      {
        levelNumber: 4,
        name: 'Full Diatonic',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 1,
        targetChallenges: 21,
        passThreshold: 0.88,
        description: 'Produce all seven diatonic scale degrees on demand.',
        pedagogicalFocus: 'Vocalize the urgent leading tone 7 and all diatonic functions.',
        tonalSupport: 'periodic',
        scaleType: 'major',
        maxInterval: 12,
      },
      {
        levelNumber: 5,
        name: 'Degree Pairs',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 2,
        targetChallenges: 16,
        passThreshold: 0.88,
        description: 'Sing two-note cells (steps, thirds, fourths) without losing tonal center.',
        pedagogicalFocus: 'Maintain internal tonic gravity across a two-note sequence.',
        tonalSupport: 'periodic',
        scaleType: 'major',
        maxInterval: 7,
      },
      {
        levelNumber: 6,
        name: 'Melodic Cells',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 3,
        targetChallenges: 12,
        passThreshold: 0.88,
        description: 'Audiate and sing compact 3-note melodic motifs.',
        pedagogicalFocus: 'Notice melodic contour and stepwise connections.',
        tonalSupport: 'periodic',
        scaleType: 'major',
        maxInterval: 7,
      },
      {
        levelNumber: 7,
        name: 'Tonal Retention',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 3,
        targetChallenges: 12,
        passThreshold: 0.90,
        description: 'Sparse tonic reinforcement: retain the tonal center internally across multiple items.',
        pedagogicalFocus: 'Tonic is provided only every ~5 challenges; rely on mental gravity.',
        tonalSupport: 'sparse',
        scaleType: 'major',
        maxInterval: 12,
      },
      {
        levelNumber: 8,
        name: 'Key Transfer',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 4,
        targetChallenges: 10,
        passThreshold: 0.90,
        description: 'Generalize production across changing keys and vocal registers.',
        pedagogicalFocus: 'Quickly recalibrate tonal center in unfamiliar keys.',
        tonalSupport: 'sparse',
        scaleType: 'major',
        maxInterval: 12,
      },
      {
        levelNumber: 9,
        name: 'Minor Function',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 3,
        targetChallenges: 12,
        passThreshold: 0.88,
        description: 'Sing functional scale degrees in natural minor context.',
        pedagogicalFocus: 'Distinguish minor flat-3, flat-6, and flat-7 functional color.',
        tonalSupport: 'periodic',
        scaleType: 'minor',
        maxInterval: 7,
      },
      {
        levelNumber: 10,
        name: 'Advanced Expansion',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 4,
        targetChallenges: 10,
        passThreshold: 0.90,
        description: 'Fast audiation and production across random keys, modes, and wider leaps.',
        pedagogicalFocus: 'Complete mastery of functional vocal audiation.',
        tonalSupport: 'sparse',
        scaleType: 'major',
        maxInterval: 12,
      },
    ],
  },

  B: {
    id: 'B',
    name: 'Degree Recognition',
    shortName: 'Recognition',
    direction: 'Hear sound · identify scale-degree function',
    mode: 'recognition',
    icon: 'Headphones',
    color: '#818cf8',
    description: 'Perceptual decoding. Hear a single pitch in context and recognize what scale-degree function it serves relative to the established tonal center.',
    levels: [
      {
        levelNumber: 1,
        name: 'Tonic vs Dominant',
        allowedDegrees: [1, 5],
        phraseLength: 1,
        targetChallenges: 24,
        passThreshold: 0.90,
        description: 'Separate the two strongest tonal poles: 1 (Home) vs 5 (Support).',
        pedagogicalFocus: 'Immediate polar recognition of home vs outward anchor.',
        tonalSupport: 'always',
        scaleType: 'major',
        maxInterval: 7,
      },
      {
        levelNumber: 2,
        name: 'Triad Anchors',
        allowedDegrees: [1, 3, 5],
        phraseLength: 1,
        targetChallenges: 24,
        passThreshold: 0.90,
        description: 'Instantly recognize tonic chord members: 1, 3, and 5.',
        pedagogicalFocus: 'Establish clear perception of stable triad tones.',
        tonalSupport: 'always',
        scaleType: 'major',
        maxInterval: 7,
      },
      {
        levelNumber: 3,
        name: 'Add Two',
        allowedDegrees: [1, 2, 3, 5],
        phraseLength: 1,
        targetChallenges: 24,
        passThreshold: 0.88,
        description: 'Introduce degree 2 as a buoyant non-chord contrast tone.',
        pedagogicalFocus: 'Differentiate 2 from neighboring 1 and 3.',
        tonalSupport: 'periodic',
        scaleType: 'major',
        maxInterval: 7,
      },
      {
        levelNumber: 4,
        name: 'Pentachord',
        allowedDegrees: [1, 2, 3, 4, 5],
        phraseLength: 1,
        targetChallenges: 22,
        passThreshold: 0.88,
        description: 'Recognize all five degrees of the lower pentachord (1–5).',
        pedagogicalFocus: 'Hear degree 4 suspension and degree 2 stepping motion.',
        tonalSupport: 'periodic',
        scaleType: 'major',
        maxInterval: 7,
      },
      {
        levelNumber: 5,
        name: 'Add Six',
        allowedDegrees: [1, 2, 3, 4, 5, 6],
        phraseLength: 1,
        targetChallenges: 22,
        passThreshold: 0.88,
        description: 'Introduce degree 6; separate it from nearby 5 and 4.',
        pedagogicalFocus: 'Discriminate degree 6 from 4 to eliminate common confusions.',
        tonalSupport: 'periodic',
        scaleType: 'major',
        maxInterval: 7,
      },
      {
        levelNumber: 6,
        name: 'All Seven',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 1,
        targetChallenges: 21,
        passThreshold: 0.88,
        description: 'Full seven-way first-attempt scale degree identification.',
        pedagogicalFocus: 'Flawless identification of all diatonic functions in major.',
        tonalSupport: 'periodic',
        scaleType: 'major',
        maxInterval: 12,
      },
      {
        levelNumber: 7,
        name: 'Sparse Tonic',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 1,
        targetChallenges: 18,
        passThreshold: 0.90,
        description: 'Maintain tonal center across multiple challenges without cadences.',
        pedagogicalFocus: 'Tonal retention under prolonged absence of external cadence.',
        tonalSupport: 'sparse',
        scaleType: 'major',
        maxInterval: 12,
      },
      {
        levelNumber: 8,
        name: 'Transfer & Timbre',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 1,
        targetChallenges: 18,
        passThreshold: 0.90,
        description: 'Generalize recognition across random keys, octaves, and timbres.',
        pedagogicalFocus: 'Timbre and register invariance for relative pitch.',
        tonalSupport: 'sparse',
        scaleType: 'major',
        maxInterval: 12,
      },
      {
        levelNumber: 9,
        name: 'Minor Recognition',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 1,
        targetChallenges: 18,
        passThreshold: 0.88,
        description: 'Recognize scale degrees in natural minor context.',
        pedagogicalFocus: 'Hear altered modal feelings in minor key.',
        tonalSupport: 'periodic',
        scaleType: 'minor',
        maxInterval: 12,
      },
      {
        levelNumber: 10,
        name: 'Mastery & Speed',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 1,
        targetChallenges: 20,
        passThreshold: 0.90,
        description: 'Instantaneous, intuitive recognition across mixed keys and registers.',
        pedagogicalFocus: 'Sub-second functional recognition.',
        tonalSupport: 'sparse',
        scaleType: 'major',
        maxInterval: 12,
      },
    ],
  },

  C: {
    id: 'C',
    name: 'Melody Singing',
    shortName: 'Melody Singing',
    direction: 'See phrase · audiate contour · sing phrase · verify',
    mode: 'melody-singing',
    icon: 'Music2',
    color: '#2dd4bf',
    description: 'Extended vocal audiation. See a sequence of scale degrees, audiate the musical phrase internally in your mind, sing the phrase, and then listen to the reference audio playback to verify.',
    levels: [
      {
        levelNumber: 1,
        name: 'Anchor Cells',
        allowedDegrees: [1, 3, 5],
        phraseLength: 3,
        targetChallenges: 12,
        passThreshold: 0.85,
        description: 'Sing 3-note stable chord-tone cells using 1, 3, and 5.',
        pedagogicalFocus: 'Audiate short arpeggios and triad contours.',
        tonalSupport: 'always',
        scaleType: 'major',
        maxInterval: 4,
      },
      {
        levelNumber: 2,
        name: 'Stepwise Pentachord',
        allowedDegrees: [1, 2, 3, 4, 5],
        phraseLength: 4,
        targetChallenges: 10,
        passThreshold: 0.85,
        description: 'Mostly stepwise 4-note melodic phrases within the lower pentachord.',
        pedagogicalFocus: 'Stepwise voice leading and simple contour shifts.',
        tonalSupport: 'periodic',
        scaleType: 'major',
        maxInterval: 2,
      },
      {
        levelNumber: 3,
        name: 'Steps + Thirds',
        allowedDegrees: [1, 2, 3, 4, 5],
        phraseLength: 5,
        targetChallenges: 10,
        passThreshold: 0.85,
        description: 'Introduce controlled skips of a third combined with stepwise movement.',
        pedagogicalFocus: 'Small skips within a 5-note phrase.',
        tonalSupport: 'periodic',
        scaleType: 'major',
        maxInterval: 4,
      },
      {
        levelNumber: 4,
        name: 'Expanded Phrase',
        allowedDegrees: [1, 2, 3, 4, 5, 6],
        phraseLength: 6,
        targetChallenges: 8,
        passThreshold: 0.88,
        description: '6-note phrases introducing degree 6 with natural cadence tendencies.',
        pedagogicalFocus: 'Musical memory span and cadential resolution (e.g. 2→1, 4→3).',
        tonalSupport: 'periodic',
        scaleType: 'major',
        maxInterval: 4,
      },
      {
        levelNumber: 5,
        name: 'Full Major Phrase',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 6,
        targetChallenges: 8,
        passThreshold: 0.88,
        description: 'Sing 6-note melodies incorporating all seven major-scale degrees.',
        pedagogicalFocus: 'Singing through the leading tone 7 within connected phrases.',
        tonalSupport: 'periodic',
        scaleType: 'major',
        maxInterval: 7,
      },
      {
        levelNumber: 6,
        name: 'Eight-Note Melody',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 8,
        targetChallenges: 7,
        passThreshold: 0.88,
        description: 'Phrase-length audiation: 8 notes with motivic repetition and contour.',
        pedagogicalFocus: 'Musical phrase memory and coherent structural shape.',
        tonalSupport: 'periodic',
        scaleType: 'major',
        maxInterval: 7,
      },
      {
        levelNumber: 7,
        name: 'Leap Control',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 8,
        targetChallenges: 6,
        passThreshold: 0.90,
        description: '8 notes with larger skips (fourths and fifths) without losing tonic.',
        pedagogicalFocus: 'Accurate leap intonation anchored to functional degrees.',
        tonalSupport: 'sparse',
        scaleType: 'major',
        maxInterval: 7,
      },
      {
        levelNumber: 8,
        name: 'Long-Form Major',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 12,
        targetChallenges: 5,
        passThreshold: 0.90,
        description: '12-note two-part musical period with antecedent and consequent.',
        pedagogicalFocus: 'Sustained working memory audiation across full musical periods.',
        tonalSupport: 'sparse',
        scaleType: 'major',
        maxInterval: 12,
      },
      {
        levelNumber: 9,
        name: 'Minor Phrases',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 8,
        targetChallenges: 6,
        passThreshold: 0.88,
        description: 'Sing expressive 8-note phrases in natural minor keys.',
        pedagogicalFocus: 'Audiation of minor tonic-mediant-dominant contours.',
        tonalSupport: 'periodic',
        scaleType: 'minor',
        maxInterval: 7,
      },
      {
        levelNumber: 10,
        name: 'Concert Audiation',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 14,
        targetChallenges: 4,
        passThreshold: 0.90,
        description: 'Advanced long-form melodies with wide leaps, sparse tonic, and changing keys.',
        pedagogicalFocus: 'Professional sight-audiation fluency.',
        tonalSupport: 'sparse',
        scaleType: 'major',
        maxInterval: 12,
      },
    ],
  },

  D: {
    id: 'D',
    name: 'Melody Transcription',
    shortName: 'Transcription',
    direction: 'Hear melody · decode degrees · enter sequence',
    mode: 'transcription',
    icon: 'PencilLine',
    color: '#a855f7',
    description: 'Melodic dictation. Hear a musical phrase played by the instrument and reconstruct the exact scale degrees on the tactile keypad.',
    levels: [
      {
        levelNumber: 1,
        name: 'Two-Note Anchors',
        allowedDegrees: [1, 3, 5],
        phraseLength: 2,
        targetChallenges: 16,
        passThreshold: 0.88,
        description: 'Hear and reconstruct two-note chord tone intervals (1, 3, 5).',
        pedagogicalFocus: 'Direct translation of heard pitch relationships into scale degrees.',
        tonalSupport: 'always',
        scaleType: 'major',
        maxInterval: 4,
      },
      {
        levelNumber: 2,
        name: 'Three-Note Cells',
        allowedDegrees: [1, 3, 5],
        phraseLength: 3,
        targetChallenges: 14,
        passThreshold: 0.88,
        description: 'Three-note chord-tone cells with contour direction changes.',
        pedagogicalFocus: 'Decode melodic shape and triad intervals.',
        tonalSupport: 'always',
        scaleType: 'major',
        maxInterval: 4,
      },
      {
        levelNumber: 3,
        name: 'Stepwise Four',
        allowedDegrees: [1, 2, 3, 4, 5],
        phraseLength: 4,
        targetChallenges: 12,
        passThreshold: 0.85,
        description: '4-note pentachord melodies with mostly adjacent movement.',
        pedagogicalFocus: 'Distinguish stepwise direction (ascending vs descending).',
        tonalSupport: 'periodic',
        scaleType: 'major',
        maxInterval: 2,
      },
      {
        levelNumber: 4,
        name: 'Mixed Four / Five',
        allowedDegrees: [1, 2, 3, 4, 5],
        phraseLength: 5,
        targetChallenges: 10,
        passThreshold: 0.88,
        description: '5-note melodies combining steps and thirds with direction changes.',
        pedagogicalFocus: 'Separating small skips from adjacent steps in auditory memory.',
        tonalSupport: 'periodic',
        scaleType: 'major',
        maxInterval: 4,
      },
      {
        levelNumber: 5,
        name: 'Six-Note Expanded',
        allowedDegrees: [1, 2, 3, 4, 5, 6],
        phraseLength: 6,
        targetChallenges: 8,
        passThreshold: 0.88,
        description: '6-note phrases incorporating degree 6.',
        pedagogicalFocus: 'Auditory memory span and functional identification of 6.',
        tonalSupport: 'periodic',
        scaleType: 'major',
        maxInterval: 4,
      },
      {
        levelNumber: 6,
        name: 'Full Diatonic Six',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 6,
        targetChallenges: 8,
        passThreshold: 0.88,
        description: '6 notes using all diatonic scale degrees.',
        pedagogicalFocus: 'Recognizing leading tone 7 and subtle tension points in sequence.',
        tonalSupport: 'periodic',
        scaleType: 'major',
        maxInterval: 7,
      },
      {
        levelNumber: 7,
        name: 'Eight-Note Melody',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 8,
        targetChallenges: 7,
        passThreshold: 0.90,
        description: 'Full 8-note musical phrases with motif, contour, and cadences.',
        pedagogicalFocus: 'Chunking melody into sub-phrases during dictation.',
        tonalSupport: 'periodic',
        scaleType: 'major',
        maxInterval: 7,
      },
      {
        levelNumber: 8,
        name: 'Advanced Major',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 10,
        targetChallenges: 6,
        passThreshold: 0.90,
        description: '10-note phrases with wider skips, sparse tonic, and changing keys.',
        pedagogicalFocus: 'Advanced melodic memory retention without repeated tonics.',
        tonalSupport: 'sparse',
        scaleType: 'major',
        maxInterval: 12,
      },
      {
        levelNumber: 9,
        name: 'Minor Transcription',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 8,
        targetChallenges: 6,
        passThreshold: 0.88,
        description: 'Dictation of 8-note phrases in natural minor.',
        pedagogicalFocus: 'Transcribing flat-3, flat-6, and flat-7 minor contours.',
        tonalSupport: 'periodic',
        scaleType: 'minor',
        maxInterval: 7,
      },
      {
        levelNumber: 10,
        name: 'Virtuoso Dictation',
        allowedDegrees: [1, 2, 3, 4, 5, 6, 7],
        phraseLength: 12,
        targetChallenges: 5,
        passThreshold: 0.90,
        description: '12-note full melodies with complex contour, leaps, and sparse scaffolding.',
        pedagogicalFocus: 'Conservatory-level melodic transcription.',
        tonalSupport: 'sparse',
        scaleType: 'major',
        maxInterval: 12,
      },
    ],
  },
};
